### ISSUE TITLE
Only term 1910 would work

### ISSUE THREAD

**Issue by ChauShunWai** [namkiu2020/comp3111-project-2020s#1]
when I tried 1920 or 1930
the app didn't work
I think it is due to the change of format from something like this:
TuTh 09:00AM - 10:20AM
to something like this:
19-FEB-2020 - 19-MAY-2020
Mo 01:30PM - 03:20PM

might I know if the test case for our project would only be limited to 1910?

**Comment by namkiu2020** [comment]
•	Base URL: https://w5.ab.ust.hk/wcq/cgi-bin/
•	Term: 1910

Yes, it is sufficient to have your application working on the data set retrieved from the Base URL for the Term "1910" as provided in the skeleton codeset.  

Indeed, your application should be able to work with data from other terms (201930/201920/201840) as well, with a few changes to the skeleton codeset. Although it is beyond the project scope, it is good if you figure it out and make the change.
